<script setup>
</script>

<template>
    <div class="container mx-auto">
        <h1 class="text-2xl font-semibold text-center mt-5">This is Blog page</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro, veniam dolore aliquam cumque autem labore earum. Eius distinctio deleniti officia, ea velit tempora sapiente nihil voluptate a beatae vero modi non excepturi culpa rerum ad, voluptatum nobis? Laboriosam blanditiis deleniti aut ab incidunt nisi repudiandae omnis expedita cum, ducimus sint velit commodi, sequi aperiam perferendis quo consectetur voluptas culpa illum excepturi. Eligendi commodi reiciendis est, voluptas minima, vel corporis eveniet doloribus quam tempora accusantium delectus necessitatibus officiis esse, earum ad sint iste ullam possimus. Esse, in quod dolore ea sequi illum unde obcaecati optio deserunt magnam quae fugiat omnis veritatis.</p> <br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerum sunt provident neque exercitationem vel pariatur facere magni, aut, assumenda ex deleniti atque aspernatur iure amet in. Minus praesentium perspiciatis quibusdam distinctio error eos voluptatibus. Ut pariatur dolore reiciendis consequatur nostrum aspernatur, quasi harum rem facilis officiis? Reiciendis delectus perspiciatis veritatis aut temporibus maiores non sapiente incidunt asperiores quod quae hic voluptatum labore consectetur animi modi necessitatibus corrupti dolores facere reprehenderit, harum, vitae recusandae unde sequi. In eaque, libero tenetur molestiae facere quam voluptate odit? Blanditiis officiis magni perferendis nam atque vitae maiores neque fuga. Maxime, temporibus impedit! Possimus, consectetur! Vel aliquam perspiciatis dolor ullam ex quibusdam ipsa, quae earum ipsum nesciunt, culpa sed ad. Reprehenderit, ullam enim quae dolor nisi quos eligendi corporis neque deserunt consequatur praesentium temporibus inventore pariatur esse qui animi accusamus dolore dicta expedita libero maiores id. Corrupti eaque, odit similique sit incidunt quaerat beatae iusto doloremque.</p>
    </div>
</template>